
# To run self hosted on ubuntu 20.04: apt install build-essential

name: Auto upload

on:
     push:
        branches:
          - Typescript
jobs:
     VerifyUpload:
          timeout-minutes: 10000
          runs-on: self-hosted
          steps:
               - name: 'Cleanup build folder'
                 run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./
               - uses: actions/checkout@v3
               - name: Use Node.js 12.x
                 uses: actions/setup-node@v3
                 with:
                    node-version: 12.x
                    cache: 'npm'
               - name: Use Python 2.7
                 uses: actions/setup-python@v3
                 with:
                    python-version: 2.7
                 env:
                    PYTHON_VERSION: 2.7
               - name: Install dependencies
                 run: |
                    npm install
                    cd server && npm install
                    cd grafana && npm install
               - name: Run build
                 run: npm run build
               - name: Get IP
                 run: hostname -I
               - name: Start Grafana instance
                 run: cd server/grafana && node index
               - name: Execute server
                 env:
                    STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
                    STEAM_ID: ${{ secrets.STEAM_ID }}
                 run: cd server && node index.js 250000
               - name: Upload code
                 env:
                    PANDAMASTER_TOKEN: ${{ secrets.PANDAMASTER_TOKEN }}
                 run: node ./uploadCode.js
